<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EditStaff.aspx.cs" Inherits="rateMyClassWeb.EditStaff" MasterPageFile="~/Master.master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="Main" runat="Server">
    <div>
        <h1>Edit Staff</h1>
    </div>
    <div class="CSSTableGenerator">
        <form runat="server">
            <asp:GridView ID="grid" runat="server" OnRowCommand="GridView1_RowCommand" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="true" AutoGenerateColumns="False" DataSourceID="RateMyClassDB" AutoGenerateEditButton="True" DataKeyNames="Staff_ID">
                <Columns>
                    <asp:BoundField DataField="Staff_ID" HeaderText="Staff ID" SortExpression="Staff_ID" InsertVisible="False" ReadOnly="True" />
                    <asp:BoundField DataField="Forename" HeaderText="Forename" SortExpression="Forename" />
                    <asp:BoundField DataField="Surname" HeaderText="Surname" SortExpression="Surname" />
                    <asp:BoundField DataField="Email_Address" HeaderText="Email_Address" SortExpression="Email_Address" />
                    
                    <asp:TemplateField HeaderText="Role" SortExpression="Role">
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlRole" runat="server" SelectedValue='<%# Eval("Role") %>'>
                                <asp:ListItem Value="lecturer">lecturer</asp:ListItem>
                                <asp:ListItem Value="dean">dean</asp:ListItem>
                                <asp:ListItem Value="admin">admin</asp:ListItem>
                            </asp:DropDownList>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblRole" runat="server" Text='<%# Eval("Role") %>' />
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                </Columns>
            </asp:GridView>
            <table>
                <tr>
                    <td>
                        <asp:Button ID="insertBtn" runat="server" Text="Add" OnClick="insertBtn_Click" />
                    </td>
                    <td>Forename:<br />
                        <asp:TextBox ID="txtForename" runat="server" />
                    </td>
                    <td>Surname:
                        <br />
                        <asp:TextBox ID="txtSurname" runat="server" />
                    </td>
                    <td>Email Address:
                        <br />
                        <asp:TextBox ID="txtEmail" runat="server" />
                    </td>
                    <td>Role:
                        <br />
                        <asp:DropDownList ID="ddlRole" runat="server">
                            <asp:ListItem>lecturer</asp:ListItem>
                            <asp:ListItem>dean</asp:ListItem>
                            <asp:ListItem>admin</asp:ListItem>
                        </asp:DropDownList>
                    </td>
                    <td>Password:
                        <br />
                        <asp:TextBox ID="txtPassword" runat="server" />
                    </td>
                </tr>
            </table>
            <asp:SqlDataSource ID="RateMyClassDB" runat="server" ConnectionString="<%$ ConnectionStrings:connString %>" ProviderName="<%$ ConnectionStrings:connString.ProviderName %>" SelectCommand="SELECT * FROM staff" DeleteCommand="DELETE FROM staff WHERE Staff_ID = @Staff_ID" InsertCommand="INSERT INTO staff (Forename, Surname, Email_Address, Role, Password) VALUES (@Forename, @Surname, @Email_Address, @Role, @Password)" UpdateCommand="UPDATE staff SET Forename = @Forename, Surname = @Surname, Email_Address = @Email_Address, Role = @Role, Password = @Password WHERE Staff_ID = @Staff_ID">
                <DeleteParameters>
                    <asp:Parameter Name="Staff_ID" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:ControlParameter Name="Forename" Type="String" ControlID="txtForename" />
                    <asp:ControlParameter Name="Surname" Type="String" ControlID="txtSurname" />
                    <asp:ControlParameter Name="Email_Address" Type="String" ControlID="txtEmail" />
                    <asp:ControlParameter Name="Password" Type="String" ControlID="txtPassword" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Forename" Type="String" />
                    <asp:Parameter Name="Surname" Type="String" />
                    <asp:Parameter Name="Email_Address" Type="String" />
                    <asp:Parameter Name="Password" Type="String" />
                    <asp:Parameter Name="Staff_ID" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </form>
    </div>
</asp:Content>
