<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EditModules.aspx.cs" Inherits="rateMyClassWeb.EditModules" MasterPageFile="~/Master.master" %>

<asp:content id="Content1" contentplaceholderid="Main" runat="Server">
    <div>
        <h1>Edit Modules</h1>
    </div>
    <div class="CSSTableGenerator">
        <form runat="server">
            <asp:GridView ID="grid" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="true" AutoGenerateColumns="False" DataSourceID="RateMyClassDB" AutoGenerateEditButton="True" DataKeyNames="Module_Code">
                <Columns>
                    <asp:BoundField DataField="Module_Code" HeaderText="Module Code" SortExpression="Module_Code" />
                    <asp:BoundField DataField="Module_Name" HeaderText="Module Name" SortExpression="Module_Name" />
                </Columns>
            </asp:GridView>
            <table>
                <tr>
                    <td>
                        <asp:Button ID="insertBtn" runat="server" Text="Add" OnClick="insertBtn_Click" />
                    </td>
                    <td>Module Code:<br />
                        <asp:TextBox ID="txtCode" runat="server" />
                    </td>
                    <td>Module Name:
                        <br />
                        <asp:TextBox ID="txtName" runat="server" />
                    </td>
                </tr>
            </table>
            <asp:SqlDataSource ID="RateMyClassDB" runat="server" ConnectionString="<%$ ConnectionStrings:connString %>" ProviderName="<%$ ConnectionStrings:connString.ProviderName %>" SelectCommand="SELECT * FROM module" DeleteCommand="DELETE FROM module WHERE Module_Code = @Module_Code" InsertCommand="INSERT INTO module (Module_Code, Module_Name) VALUES (@Module_Code, @Module_Name)" UpdateCommand="UPDATE module SET Module_Code = @Module_Code, Module_Name = @Module_Name WHERE Module_Code = @Module_Code">
                <DeleteParameters>
                    <asp:Parameter Name="Module_Code" Type="String" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:ControlParameter Name="Module_Code" Type="String" ControlID="txtCode" />
                    <asp:ControlParameter Name="Module_Name" Type="String" ControlID="txtName" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Module_Code" Type="String" />
                    <asp:Parameter Name="Module_Name" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </form>
    </div>
</asp:content>
