<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EditTeachings.aspx.cs" Inherits="rateMyClassWeb.EditTeachings" MasterPageFile="~/Master.master" %>

<asp:content id="Content1" contentplaceholderid="Main" runat="Server">
    <a href="Login.aspx"><- Back</a>
    <div>
        <h1>Edit Teaching Assignments</h1>
    </div>
    <div class="CSSTableGenerator">
        <form runat="server">
            <asp:GridView ID="grid" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="true" AutoGenerateColumns="False" DataSourceID="RateMyClassDB" DataKeyNames="Teaching_ID">
                <Columns>
                    <asp:BoundField DataField="Teaching_ID" HeaderText="Teaching ID" SortExpression="Teaching_ID" InsertVisible="False" ReadOnly="True" />
                    <asp:TemplateField HeaderText="Module_Code" SortExpression="Module_Code">
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlModule" runat="server" SelectedValue='<%# Eval("Module_Code") + " - " + Eval("Module_Name") %>' />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblModule" runat="server" Text='<%# Eval("Module_Code") + " - " + Eval("Module_Name") %>' />
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Staff Member" SortExpression="Staff_ID">
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlStaff" runat="server" SelectedValue='<%# Eval("Forename") + " " + Eval("Surname") %>' />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblStaff" runat="server" Text='<%# Eval("Forename") + " " + Eval("Surname") %>' />
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <table>
                <tr>
                    <td>
                        <asp:Button ID="insertBtn" runat="server" Text="Add" OnClick="insertBtn_Click" />
                    </td>
                    <td>Module Code:<br />
                        <asp:DropDownList ID="ddlModule2" runat="server" />
                    </td>
                    <td>Staff ID:
                        <br />
                        <asp:DropDownList ID="ddlStaff2" runat="server" />
                    </td>
                </tr>
            </table>
            <asp:SqlDataSource ID="RateMyClassDB" runat="server" ConnectionString="<%$ ConnectionStrings:connString %>" ProviderName="<%$ ConnectionStrings:connString.ProviderName %>" SelectCommand="SELECT teaching.*, module.Module_Name, staff.Forename, staff.Surname FROM teaching INNER JOIN module ON teaching.Module_Code=module.Module_Code INNER JOIN staff ON teaching.Staff_ID=staff.Staff_ID ORDER BY teaching.Module_Code ASC" DeleteCommand="DELETE FROM teaching WHERE Teaching_ID = @Teaching_ID" InsertCommand="INSERT INTO teaching (Module_Code, Staff_ID) VALUES (@Module_Code, @Staff_ID)" UpdateCommand="UPDATE teaching SET Module_Code = @Module_Code, Staff_ID = @Staff_ID WHERE Teaching_ID = @Teaching_ID">
                <DeleteParameters>
                    <asp:Parameter Name="Teaching_ID" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Module_Code" Type="String" />
                    <asp:Parameter Name="Staff_ID" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </form>
    </div>
</asp:content>
